### PR TITLE
Port staff page to React

### LINKED ISSUE #48: Make staff page view in React

### LINKED ISSUE #62: Missing Profile Pictures
## Describe the bug
Outdated images for Brussles and 8-Bit on the staff page, mean they don't display currently

## To Reproduce
Go to staff page.
Brussles under Admins has a missing image, and 8-Bit under Moderators has a missing image.

## Additional context
Current profile pictures are:
Brussles: https://cdn.discordapp.com/avatars/608641641284370462/9c6698249645077608227af19f0673b2.webp?size=128
8-Bit: https://cdn.discordapp.com/avatars/711997187290300546/4d491b9f6f5ff4b4465dd0bb325d2ca0.webp?size=128

### LINKED ISSUE #63: Add new CoCos!
## Purpose
The new CoCos need to be added to the staff page!

## Proposed Solution
I'll probably include this in my PR for the staff page this weekend (sorry for the long delay) although if someone would rather tackle it separately by all means go ahead!

It also might be nice to hold off and see if the CoCos want to add it themselves, after the page is ported (should just be editing a .json so nothing difficult)

### PR DESCRIPTION
**Pull request by lyallstewart**
## What issue is this solving?

Closes #48
Closes #63 
Closes #62 

### Description
1. Ports the old `staff.html` file into a React component and moves the relevant data into a JSON file.
2. Adds the new CoCos
3. Fixes Brussels' and 8-Bit's profile pictures (credit to @Shaylin-8bit 😄)

## Any helpful knowledge/context for the reviewer?

- Any new dependencies to install? ❌ 
- Any special requirements to test? ❌ 

### Please make sure you've attempted to meet the following coding standards

- [X] Code has been tested and does not produce errors
- [X] Code is readable and formatted
- [X] There isn't any unnecessary commented-out code

### CODE REVIEW

File: src/Views/Staff.jsx [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+    return (
+       <main className="has-text-centered title">
+           <h1 className="is-size-1 pagetitle">Codecademy Community Server Staff</h1>
+           <p className="is-size-4 mb-3">Meet our server staff!</p>
+           <section className="container has-background-white mb-6 p-3">
+               <h2 className="is-size-2">Admins</h2>
+               <p>Admins are the heads of our staff and the people who manage how the group is run.</p>
+               <div className="staff-list">
+                   {
+                       data["superadmins"].map((user) => {
```
Comment (lyallstewart) [inline src/Views/Staff.jsx:14]: Ideally these would be ported over to a `<StaffCard />` Component too with data as props but I felt this PR was already fairly long and would be best addressed in a follow up.

File: src/Views/Staff.jsx [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+               <div className="staff-list">
+                    {
+                       data["mods"].map((user) => {
+                        return <div className="staff-card has-background-white">
+                                <img className="profile-picture" src={user[1]}/>
+                                <p className="name mod">{user[0]}</p>
+                            </div>
+                        })
+                    }
+                    <div className="staff-card has-background-white">
```
Comment (lyallstewart) [inline src/Views/Staff.jsx:43]: Due to tgrtim's profile picture being stored locally (thanks to weirdness with how Discord themselves store blank pfps) it cannot be handled the normal way with a URL so must be done separately by manually importing the image.
This isn't great but is fine for now, although is something we probably should find a better work around for in future

File: src/assets/sass/views/_staff.scss [hunk 3]
```diff
@@ -58,3 +58,7 @@ p {
     background-color: white;
     height: 500px;
 }
+
+p {
```
Comment (aedwardg) [inline src/assets/sass/views/_staff.scss:62]: I'm curious if we should be adding styling to the <p> tag here instead of just creating a regular class and adding that.  I believe this will override the font-size for `<p>` everywhere else too.  But if we like that size for all paragraph text we can always move that to a better spot.  Alternatively, we can use CSS module syntax here and scope it to the component we want it in.

We can leave it here for now though, this is low-priority as long as it doesn't break existing pages.

File: src/data/staff.json [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+            "https://cdn.discordapp.com/avatars/543076845919404034/a6cd050c4d6f5f3b1b2036595e4f1730.webp?size=128"
+        ],
+        [
+            "Lyall (he/him) [Bristol CL]",
+            "https://cdn.discordapp.com/avatars/715846451334217728/cacae335b4d9aa9bf6924a8d85368812.webp?size=128"
+        ]
+    ],
+    "cocos": [
+        [
+            "megara | Rachel (she/her",
```
Comment (aedwardg) [inline src/data/staff.json:46]: )

File: src/data/staff.json [hunk 5]
```diff
@@ -0,0 +1,78 @@
+{   
+   "superadmins": [ 
+        [
+            "brussels",
+            "https://cdn.discordapp.com/avatars/608641641284370462/9c6698249645077608227af19f0673b2.webp?size=80"
+        ],
```
Comment (aedwardg) [inline src/data/staff.json:6]: This works okay, but I think this would be better as an object instead of an array.  That way we can access by key when you map through them:
```
user["name"], user["imgUrl"], user["bio"]...
```

**Review by aedwardg — COMMENTED** [review]
Great job @lyallstewart , this is almost there.
I left a couple of comments that I think we should take care of first before merging.

File: src/data/staff.json [hunk 6]
```diff
@@ -0,0 +1,78 @@
...
+            "UnseenCode",
+            "https://cdn.discordapp.com/avatars/821869015143284766/fdf38925ee209ce9bd95a1e74f03a55e.webp?size=80"
+        ],
+        [
+            "Christo (he/him)",
+            "https://cdn.discordapp.com/avatars/225808309343617025/6659ece3ae53ac3778d9d20608c231a3.webp?size=80"
+        ],
+        [
+            "Hunter The Milk Turtle",
+            "https://cdn.discordapp.com/avatars/225808309343617025/6659ece3ae53ac3778d9d20608c231a3.webp?size=80"
```
Comment (Victoria-DR) [inline src/data/staff.json:67]: Looks like this links to Christo's profile picture instead of Hunter's.

File: src/data/staff.json [hunk 7]
```diff
@@ -0,0 +1,78 @@
...
+        ],
+        [
+            "MikeJ",
+            "https://cdn.discordapp.com/avatars/833832122207698945/9d86a57fc85b87af9f77ee59846fa2a1.webp?size=128"
+        ],
+        [
+            "Subz",
```
Comment (Victoria-DR) [inline src/data/staff.json:74]: Small thing but should be lowercase.

File: src/Views/Staff.jsx [hunk 8]
```diff
@@ -0,0 +1,67 @@
...
+           </section>
+           <section className="container has-background-white mb-6 p-3">
+               <h2 className="is-size-2">Code Counselors</h2>
+               <p>Code Counselors are members of the community who have been recognised as being the most active, friendly and helpful.</p>
+               <div className="staff-list">
+                    {
+                       data["cocos"].map((user) => {
+                        return <div className="staff-card has-background-white">
+                                <img className="profile-picture" src={user[1]}/>
+                                <p className="name mod">{user[0]}</p>
```
Comment (Victoria-DR) [inline src/Views/Staff.jsx:58]: Looks like the `mod` class styling is being applied instead of the `coco` one.

**Review by Victoria-DR — COMMENTED** [review]
Looks great, thanks! In addition to what @aedwardg has said, there are just a couple more minor bugs I found.

**Comment by lyallstewart** [comment]
Thanks for the reviews! Those should all be corrected now 🙂

**Review by aedwardg — APPROVED** [review]
LGTM! Thanks for making those changes!

**Comment by mikejoh12** [comment]
I am getting a console warning on Staff React page: Warning: Each child in a list should have a unique "key" prop. My understanding is React uses this key prop internally for rendering optimizations so it's good to provide.

React likes the key prop for using .map on lists. Perhaps one options is to just use the user-name as a key prop for the 4 .map methods since they will be unique: key={user["name"]}

**Comment by lyallstewart** [comment]
My bad probably should've checked the console first 🤦‍♂️. As suggested I've added the name as a key for each `.map` method. Thanks! 😄

**Comment by mikejoh12** [comment]
Looks good to me!

**Review by mikejoh12 — APPROVED** [review]

**Comment by lyallstewart** [comment]
Thanks!
