### PR TITLE
make footer sticky

### LINKED ISSUE #43: Footer is not "sticky" on high resolution screens
## Describe the bug
Currently in high resolution screens (e.g., WQHD, UHD, WUHD) the footer does not appear all the way at the bottom of the page.

## Expected behavior
Footer should stay on the bottom no matter the screen resolution or zoom value

## To Reproduce
If you're on a high res screen (higher than 1080p):
1. Go to website
2. See footer issue

If you're on 1080p or lower:
1. Go to website
2. Set browser zoom to something less than 100%
3. See footer issue

### Screenshots
Screen Shot 2021-12-13 at 10 59 37 AM

**Desktop (please complete the following information if applicable):**
 - OS: Windows/MacOS
 - Browser: Firefox

## Potential solution
I think the answers in this SO thread should solve the problem:
https://stackoverflow.com/questions/43727032/hero-footer-not-at-bottom-of-page

### PR DESCRIPTION
**Pull request by mikejoh12**
## What issue is this solving?

Closes #43

### Description

Previous footer was not sticking to bottom. Wrapped page in min-height 100vh and used bulma helpers for column flex-box to make main content expand and push footer to bottom. Deleted adjustment to footer padding so footer text is more easily seen. After change, there is a slight vertical scroll-bar present even on short page-content (first page). Could not remove this but it's relatively minor compared to previous appearance. 

Inspired by: https://blog.cetindere.de/make-footers-stick-to-the-bottom-of-the-page-in-bulma/

### Please make sure you've attempted to meet the following coding standards

- [X] Code has been tested and does not produce errors
- [X] Code is readable and formatted
- [X] There isn't any unnecessary commented-out code

### CODE REVIEW

**Review by lyallstewart — CHANGES_REQUESTED** [review]
Looks great! Just one small thing I think we should get on before merging this:

It seems like on larger screen resolutions (I tested on 1440p) the footer becomes a lot thicker, with a gap at the bottom:
image

If possible I'd ideally prefer it if we could getting it looking more like it does currently (note screenshot from a lower resolution) without the extra thickness and gap: 😄 
image

File: src/App.jsx [hunk 1]
```diff
@@ -14,16 +14,24 @@ function App() {
...
-          <Route path="/" element={<Home />} />
-          <Route path="/staff" element={<Staff />} />
-          <Route path="/contact" element={<Contact />} />
-          <Route path="/sharing-code" element={<SharingCode />} />
-          <Route path="/getting-help" element={<GettingHelp />} />
-          <Route path="/faq" element={<FAQ />} />
-        </Routes>
-        <Footer />
+        <div className="columns is-flex-direction-column page-wrapper">
+          <div className="column is-narrow">
```
[the remark this answers is not in the document]
Comment (mikejoh12) [reply src/App.jsx:18]: Removing is-narrow from footer and header and then viewing on a tall screen causes header, main-content, and footer all to be centered. This can be checked by zooming out to 50% in browser. Leaving is-narrow for header and footer keeps them at the top/bottom.

**Comment by mikejoh12** [comment]
> Looks great! Just one small thing I think we should get on before merging this:
> 
> It seems like on larger screen resolutions (I tested on 1440p) the footer becomes a lot thicker, with a gap at the bottom: image
> 
> If possible I'd ideally prefer it if we could getting it looking more like it does currently (note screenshot from a lower resolution) without the extra thickness and gap: 😄 image

I think those 2 issues should be resolved now.

File: src/index.js [hunk 2]
```diff
@@ -1,6 +1,5 @@
 import React from 'react';
 import ReactDOM from 'react-dom';
-import './index.css';
```
Comment (aedwardg) [inline src/index.js:3]: ❤️ deleted code. Good catch on the unused `index.css` and `App.css`!

File: src/App.jsx [hunk 3]
```diff
@@ -14,16 +14,24 @@ function App() {
...
-        <Routes>
-          <Route path="/" element={<Home />} />
-          <Route path="/staff" element={<Staff />} />
-          <Route path="/contact" element={<Contact />} />
-          <Route path="/sharing-code" element={<SharingCode />} />
-          <Route path="/getting-help" element={<GettingHelp />} />
-          <Route path="/faq" element={<FAQ />} />
-        </Routes>
-        <Footer />
+        <div className="columns is-flex-direction-column page-wrapper my-0">
```
Comment (aedwardg) [inline src/App.jsx:17]: I like the use of the bulma flex helper here!

**Review by aedwardg — COMMENTED** [review]
I think this does solve the problem, but I'm not sure if it is the best way to go about it.
Left some comments in Discord: https://discord.com/channels/810930683732033597/848577858388492298/941581517002506260

Would love to discuss this further!

**Review by aedwardg — APPROVED** [review]
New changes look good. I think we learned a lot by going through this issue and uncovered some great new improvements we can make. Also, CSS is hard 🙂.

**Review by lyallstewart — APPROVED** [review]
LGTM! Great job getting it sorted out!

>  Also, CSS is hard 🙂.

Could not agree more there!
